parameters:
  sensorConf:
    type: 'https://www.w3.org/TR/vocab-ssn/#SOSASensor'
    spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Document'
    nameType: 'sensor'
    fields:
      # http://virtual-assembly.org/pair#subjectOf_Pair:
      #   value: 'subjectOfPAIR'
      #   access: 'anonymous'
      #   type: 'uri'
      http://virtual-assembly.org/pair#preferedLabel:
        value: 'preferedLabel'
        access: 'anonymous'
      http://virtual-assembly.org/pair#alternativeLabel:
        value: 'alternativeLabel'
        access: 'anonymous'
      http://virtual-assembly.org/pair#documents:
        value: 'documents'
        access: 'anonymous'
        type: 'uri'
      http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
        value: 'type'
        access: 'anonymous'

    reverse:
      http://virtual-assembly.org/pair#documents: 'http://virtual-assembly.org/pair#documentedBy'
    label:
      - http://virtual-assembly.org/pair#preferedLabel